name: SaltspringSolar
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4626
title: Saltspring Solar Ltd.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a8e8fd'
    - '#ffffff'
    - '#1b3356'
    - '#7d8a9e'
    - '#8ab9d0'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
